import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  button: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#1f7a5c",
    borderRadius: 8,
    minWidth: 120,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  content: {
    flexGrow: 1,
    gap: 20,
    padding: 24,
    paddingTop: 72,
  },
  disabledButton: {
    opacity: 0.6,
  },
  errorText: {
    color: "#9c2f23",
    fontSize: 14,
    lineHeight: 20,
  },
  dateText: {
    color: "#7a7067",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  googleButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 190,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  googleButtonText: {
    color: "#171412",
    fontSize: 16,
    fontWeight: "700",
  },
  holoBadge: {
    backgroundColor: "rgba(247, 244, 238, 0.84)",
    borderRadius: 999,
    color: "#171412",
    fontSize: 11,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: "uppercase",
  },
  holoCard: {
    backgroundColor: "#171412",
    borderColor: "#f7d37a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    overflow: "hidden",
    padding: 16,
    shadowColor: "#000000",
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
  },
  holoCardBorder: {
    ...StyleSheet.absoluteFillObject,
    borderColor: "rgba(255, 255, 255, 0.34)",
    borderRadius: 8,
    borderWidth: 1,
  },
  holoCardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 2,
  },
  holoEyebrow: {
    color: "#bfe8d7",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  holoInitials: {
    alignItems: "center",
    backgroundColor: "#f7f4ee",
    flex: 1,
    justifyContent: "center",
  },
  holoInitialsText: {
    color: "#171412",
    fontSize: 46,
    fontWeight: "900",
  },
  holoName: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
  },
  holoPortrait: {
    height: "100%",
    width: "100%",
  },
  holoPortraitFrame: {
    aspectRatio: 1.56,
    backgroundColor: "rgba(247, 244, 238, 0.12)",
    borderColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
    zIndex: 2,
  },
  holoShine: {
    backgroundColor: "rgba(255, 255, 255, 0.28)",
    height: 260,
    left: "36%",
    opacity: 0.8,
    position: "absolute",
    top: -60,
    width: 56,
  },
  holoSpeckle: {
    borderRadius: 999,
    height: 140,
    opacity: 0.28,
    position: "absolute",
    width: 140,
  },
  holoSpeckleBlue: {
    backgroundColor: "#8bb8ff",
    bottom: -48,
    right: -28,
  },
  holoSpeckleGreen: {
    backgroundColor: "#83f0b6",
    left: -54,
    top: 58,
  },
  holoSpeckleLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(125, 82, 255, 0.13)",
  },
  holoSpecklePink: {
    backgroundColor: "#ff8fc3",
    right: 20,
    top: -54,
  },
  holoStat: {
    backgroundColor: "rgba(247, 244, 238, 0.9)",
    borderRadius: 8,
    flex: 1,
    gap: 2,
    padding: 10,
  },
  holoStatsRow: {
    flexDirection: "row",
    gap: 8,
    zIndex: 2,
  },
  holoStatLabel: {
    color: "#5f564d",
    fontSize: 11,
    fontWeight: "800",
  },
  holoStatValue: {
    color: "#171412",
    fontSize: 20,
    fontWeight: "900",
  },
  itemTitle: {
    color: "#171412",
    fontSize: 16,
    fontWeight: "700",
  },
  librarySection: {
    gap: 16,
  },
  listItem: {
    alignItems: "center",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  listSection: {
    gap: 10,
  },
  listText: {
    flex: 1,
    gap: 4,
  },
  listTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "800",
  },
  progressText: {
    color: "#1f7a5c",
    fontSize: 14,
    fontWeight: "800",
  },
  pressedListItem: {
    opacity: 0.72,
  },
  screen: {
    backgroundColor: "#f7f4ee",
    flex: 1,
  },
  sectionEyebrow: {
    color: "#1f7a5c",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  sectionTitle: {
    color: "#171412",
    fontSize: 26,
    fontWeight: "800",
  },
  secondaryButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#171412",
    borderRadius: 8,
    minWidth: 120,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  statusDetail: {
    color: "#5f564d",
    fontSize: 14,
    lineHeight: 20,
  },
  statusLabel: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "700",
  },
  statusPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  subtitle: {
    color: "#4f4740",
    fontSize: 17,
    lineHeight: 24,
  },
  title: {
    color: "#171412",
    fontSize: 42,
    fontWeight: "800",
  },
});
