import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actionListItem: {
    backgroundColor: "#f7f4ee",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  accountActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingTop: 4,
  },
  appleSignInButton: {
    alignSelf: "flex-start",
    height: 44,
    width: 230,
  },
  authButtons: {
    alignItems: "flex-start",
    gap: 10,
    paddingTop: 4,
  },
  content: {
    flexGrow: 1,
    gap: 20,
    padding: 24,
    paddingBottom: 32,
    paddingTop: 72,
  },
  countryOptionButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    minWidth: 78,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  countryOptionButtonSelected: {
    backgroundColor: "#e5f3ed",
    borderColor: "#1f7a5c",
  },
  countryOptionText: {
    color: "#5f564d",
    fontSize: 14,
    fontWeight: "800",
  },
  countryOptionTextSelected: {
    color: "#1f7a5c",
  },
  countryOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 4,
  },
  disabledButton: {
    opacity: 0.6,
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#9c2f23",
    borderRadius: 8,
    minHeight: 44,
    minWidth: 140,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  dangerButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  dangerOutlineButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#9c2f23",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 44,
    minWidth: 140,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  dangerOutlineButtonText: {
    color: "#9c2f23",
    fontSize: 16,
    fontWeight: "800",
  },
  errorText: {
    color: "#9c2f23",
    fontSize: 14,
    lineHeight: 20,
  },
  fixedContent: {
    flex: 1,
    gap: 20,
    padding: 24,
    paddingBottom: 16,
    paddingTop: 72,
  },
  emptyPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  googleButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 230,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  googleButtonText: {
    color: "#171412",
    fontSize: 16,
    fontWeight: "700",
  },
  groupPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  groupSeason: {
    gap: 8,
  },
  groupSeasonHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 2,
  },
  groupSeasonLink: {
    flex: 1,
    paddingVertical: 6,
  },
  groupSeasonMeta: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  groupSubtitle: {
    color: "#5f564d",
    fontSize: 13,
    fontWeight: "800",
  },
  groupSeasonToggle: {
    color: "#1f7a5c",
    fontSize: 18,
    fontWeight: "900",
    minWidth: 18,
    textAlign: "right",
  },
  groupSeasonToggleButton: {
    alignItems: "flex-end",
    justifyContent: "center",
    minHeight: 32,
    minWidth: 32,
  },
  groupTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "900",
  },
  groupTitleLink: {
    alignSelf: "flex-start",
    paddingVertical: 2,
  },
  holoBadge: {
    backgroundColor: "rgba(247, 244, 238, 0.84)",
    borderRadius: 999,
    color: "#171412",
    fontSize: 11,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: "uppercase",
  },
  holoCard: {
    backgroundColor: "#171412",
    borderColor: "#f7d37a",
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    overflow: "hidden",
    padding: 16,
    shadowColor: "#000000",
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
  },
  holoCardBorder: {
    ...StyleSheet.absoluteFillObject,
    borderColor: "rgba(255, 255, 255, 0.34)",
    borderRadius: 8,
    borderWidth: 1,
  },
  holoCardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 2,
  },
  holoEyebrow: {
    color: "#bfe8d7",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  holoInitials: {
    alignItems: "center",
    backgroundColor: "#f7f4ee",
    flex: 1,
    justifyContent: "center",
  },
  holoInitialsText: {
    color: "#171412",
    fontSize: 46,
    fontWeight: "900",
  },
  holoName: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
  },
  holoPortrait: {
    height: "100%",
    width: "100%",
  },
  holoPortraitFrame: {
    aspectRatio: 1.56,
    backgroundColor: "rgba(247, 244, 238, 0.12)",
    borderColor: "rgba(255, 255, 255, 0.38)",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
    zIndex: 2,
  },
  holoPortraitSkeleton: {
    backgroundColor: "#e3ddd3",
  },
  holoShine: {
    backgroundColor: "rgba(255, 255, 255, 0.28)",
    height: 260,
    left: "36%",
    opacity: 0.8,
    position: "absolute",
    top: -60,
    width: 56,
  },
  holoSpeckle: {
    borderRadius: 999,
    height: 140,
    opacity: 0.28,
    position: "absolute",
    width: 140,
  },
  holoSpeckleBlue: {
    backgroundColor: "#8bb8ff",
    bottom: -48,
    right: -28,
  },
  holoSpeckleGreen: {
    backgroundColor: "#83f0b6",
    left: -54,
    top: 58,
  },
  holoSpeckleLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(125, 82, 255, 0.13)",
  },
  holoSpecklePink: {
    backgroundColor: "#ff8fc3",
    right: 20,
    top: -54,
  },
  holoSkeletonHeaderText: {
    flex: 1,
    gap: 6,
  },
  holoStat: {
    backgroundColor: "rgba(247, 244, 238, 0.9)",
    borderRadius: 8,
    flex: 1,
    gap: 2,
    padding: 10,
  },
  holoStatsRow: {
    flexDirection: "row",
    gap: 8,
    zIndex: 2,
  },
  holoStatLabel: {
    color: "#5f564d",
    fontSize: 11,
    fontWeight: "800",
  },
  holoStatValue: {
    color: "#171412",
    fontSize: 20,
    fontWeight: "900",
  },
  headerRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14,
    justifyContent: "space-between",
  },
  headerText: {
    flex: 1,
    gap: 8,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#1f7a5c",
    borderRadius: 8,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  iconButtonText: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 28,
  },
  itemTitle: {
    color: "#171412",
    fontSize: 16,
    fontWeight: "700",
  },
  librarySection: {
    gap: 16,
  },
  librarySectionFixed: {
    flex: 1,
    gap: 16,
  },
  legalLinkButton: {
    backgroundColor: "#ffffff",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  legalLinkText: {
    color: "#1f7a5c",
    fontSize: 14,
    fontWeight: "800",
  },
  legalLinksRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 4,
  },
  libraryListContent: {
    gap: 16,
    paddingBottom: 8,
  },
  libraryListScroll: {
    flex: 1,
  },
  listItem: {
    alignItems: "center",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  listSection: {
    gap: 10,
  },
  listText: {
    flex: 1,
    gap: 4,
  },
  listTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "800",
  },
  pressedListItem: {
    opacity: 0.72,
  },
  recommendationListItem: {
    alignItems: "center",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    padding: 12,
  },
  recommendationText: {
    flex: 1,
    gap: 4,
  },
  recommendationCountPill: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#b8ddcd",
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 34,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  recommendationCountText: {
    color: "#1f7a5c",
    fontSize: 14,
    fontWeight: "900",
  },
  recommendationDetail: {
    color: "#5f564d",
    fontSize: 13,
    lineHeight: 18,
  },
  recommendationEyebrow: {
    color: "#1f7a5c",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  recommendationHeader: {
    alignItems: "center",
    backgroundColor: "#e8f3ed",
    borderColor: "#b8ddcd",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 14,
  },
  recommendationHeaderText: {
    flex: 1,
    gap: 2,
  },
  recommendationIconFrame: {
    alignItems: "center",
    backgroundColor: "#1f7a5c",
    borderRadius: 999,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  recommendationScorePill: {
    alignItems: "center",
    borderColor: "#b8ddcd",
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 34,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  recommendationTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "900",
  },
  screen: {
    backgroundColor: "#f7f4ee",
    flex: 1,
  },
  sectionEyebrow: {
    color: "#1f7a5c",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  sectionTitle: {
    color: "#171412",
    fontSize: 26,
    fontWeight: "800",
  },
  secondaryButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#171412",
    borderRadius: 8,
    minWidth: 120,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  skeletonBadge: {
    borderRadius: 999,
    height: 26,
    width: 58,
  },
  skeletonCard: {
    backgroundColor: "#ece7dd",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  skeletonCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  skeletonMediaRow: {
    alignItems: "center",
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  skeletonMediaText: {
    flex: 1,
    gap: 8,
  },
  skeletonPortrait: {
    aspectRatio: 1.56,
  },
  skeletonShortLine: {
    height: 18,
    width: 150,
  },
  skeletonStat: {
    flexBasis: "30%",
    flexGrow: 1,
  },
  statusDetail: {
    color: "#5f564d",
    fontSize: 14,
    lineHeight: 20,
  },
  statusLabel: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "700",
  },
  statusPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  swipeActionButton: {
    alignItems: "center",
    backgroundColor: "#9c2f23",
    borderRadius: 8,
    justifyContent: "center",
    minWidth: 124,
    paddingHorizontal: 14,
  },
  swipeActionButtonArmed: {
    backgroundColor: "#6f1f18",
  },
  swipeActionButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  swipeActions: {
    flexDirection: "row",
    marginLeft: 8,
  },
  swipeableRow: {
    borderRadius: 8,
  },
  subtitle: {
    color: "#4f4740",
    fontSize: 17,
    lineHeight: 24,
  },
  title: {
    color: "#171412",
    fontSize: 42,
    fontWeight: "800",
  },
});
