import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  activeFilterButton: {
    backgroundColor: "#171412",
    borderColor: "#171412",
  },
  activeFilterText: {
    color: "#ffffff",
  },
  content: {
    flexGrow: 1,
    gap: 20,
    padding: 24,
    paddingBottom: 32,
    paddingTop: 64,
  },
  disabledButton: {
    opacity: 0.6,
  },
  errorText: {
    color: "#9c2f23",
    fontSize: 13,
    lineHeight: 18,
  },
  filterButton: {
    alignItems: "center",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 10,
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
  },
  filterText: {
    color: "#171412",
    fontSize: 14,
    fontWeight: "800",
  },
  header: {
    gap: 8,
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    color: "#171412",
    fontSize: 17,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  loadingStrip: {
    alignItems: "center",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  loadingText: {
    color: "#5f564d",
    fontSize: 14,
    fontWeight: "700",
  },
  mediaPill: {
    alignSelf: "flex-start",
    backgroundColor: "#e4f1ea",
    borderRadius: 8,
    color: "#1f7a5c",
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mutedText: {
    color: "#5f564d",
    fontSize: 14,
    lineHeight: 20,
  },
  pendingFilterButton: {
    opacity: 0.72,
  },
  poster: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 112,
    width: 76,
  },
  posterPlaceholder: {
    alignItems: "center",
    backgroundColor: "#e8e2d8",
    borderRadius: 8,
    height: 112,
    justifyContent: "center",
    width: 76,
  },
  posterPlaceholderText: {
    color: "#5f564d",
    fontSize: 18,
    fontWeight: "800",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#1f7a5c",
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  resolveButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#171412",
    borderRadius: 8,
    minWidth: 108,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  resolveButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  resultBody: {
    flex: 1,
    gap: 7,
  },
  resultHeading: {
    gap: 6,
  },
  resultMeta: {
    color: "#7a7067",
    fontSize: 13,
    fontWeight: "700",
  },
  resultOverview: {
    color: "#5f564d",
    fontSize: 14,
    lineHeight: 19,
  },
  resultRow: {
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    padding: 12,
  },
  resultTitle: {
    color: "#171412",
    flexShrink: 1,
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 22,
  },
  resultsHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  resultsSection: {
    gap: 12,
  },
  screen: {
    backgroundColor: "#f7f4ee",
    flex: 1,
  },
  searchPanel: {
    gap: 12,
  },
  sectionTitle: {
    color: "#171412",
    flex: 1,
    fontSize: 20,
    fontWeight: "800",
  },
  skeletonBody: {
    flex: 1,
    gap: 10,
  },
  skeletonButton: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 34,
    width: 96,
  },
  skeletonLine: {
    backgroundColor: "#e2dbd1",
    borderRadius: 8,
    height: 14,
    width: "92%",
  },
  skeletonLineShort: {
    backgroundColor: "#e2dbd1",
    borderRadius: 8,
    height: 14,
    width: "62%",
  },
  skeletonList: {
    gap: 12,
  },
  skeletonPoster: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 112,
    width: 76,
  },
  skeletonRow: {
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    padding: 12,
  },
  skeletonTitle: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 20,
    width: "72%",
  },
  statusPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  statusTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "800",
  },
  subtitle: {
    color: "#4f4740",
    fontSize: 17,
    lineHeight: 24,
  },
  title: {
    color: "#171412",
    fontSize: 42,
    fontWeight: "800",
  },
  tvloreText: {
    color: "#1f7a5c",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
});
