import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  backButton: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backButtonText: {
    color: "#1f7a5c",
    fontSize: 16,
    fontWeight: "800",
  },
  clearButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  clearButtonText: {
    color: "#5f564d",
    fontSize: 14,
    fontWeight: "800",
  },
  disabledButton: {
    opacity: 0.6,
  },
  errorText: {
    color: "#9c2f23",
    fontSize: 14,
    lineHeight: 20,
  },
  content: {
    flexGrow: 1,
    gap: 20,
    padding: 24,
    paddingTop: 48,
  },
  detail: {
    gap: 20,
  },
  hero: {
    flexDirection: "row",
    gap: 16,
  },
  heroText: {
    flex: 1,
    gap: 8,
    justifyContent: "center",
  },
  mediaPill: {
    alignSelf: "flex-start",
    backgroundColor: "#e4f1ea",
    borderRadius: 8,
    color: "#1f7a5c",
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mutedText: {
    color: "#5f564d",
    fontSize: 14,
    lineHeight: 20,
  },
  overview: {
    color: "#302b27",
    fontSize: 16,
    lineHeight: 23,
  },
  poster: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 168,
    width: 114,
  },
  posterPlaceholder: {
    alignItems: "center",
    backgroundColor: "#e8e2d8",
    borderRadius: 8,
    height: 168,
    justifyContent: "center",
    width: 114,
  },
  posterPlaceholderText: {
    color: "#5f564d",
    fontSize: 22,
    fontWeight: "800",
  },
  pressedSeasonRow: {
    opacity: 0.72,
  },
  primaryButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#1f7a5c",
    borderRadius: 8,
    minWidth: 108,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  ratingButton: {
    alignItems: "center",
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  ratingButtonSelected: {
    backgroundColor: "#1f7a5c",
    borderColor: "#1f7a5c",
  },
  ratingButtonText: {
    color: "#302b27",
    fontSize: 16,
    fontWeight: "800",
  },
  ratingButtonTextSelected: {
    color: "#ffffff",
  },
  ratingRow: {
    flexDirection: "row",
    gap: 8,
  },
  screen: {
    backgroundColor: "#f7f4ee",
    flex: 1,
  },
  seasonBody: {
    flex: 1,
    gap: 4,
  },
  seasonRow: {
    alignItems: "center",
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  seasonTitle: {
    color: "#171412",
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 22,
  },
  seasonsSection: {
    gap: 12,
  },
  secondaryButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#171412",
    borderRadius: 8,
    minWidth: 136,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  sectionTitle: {
    color: "#171412",
    fontSize: 20,
    fontWeight: "800",
  },
  skeletonButton: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 38,
    width: 132,
  },
  skeletonHeroText: {
    flex: 1,
    gap: 10,
    justifyContent: "center",
  },
  skeletonLineMedium: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 16,
    width: "70%",
  },
  skeletonLineShort: {
    backgroundColor: "#e2dbd1",
    borderRadius: 8,
    height: 14,
    width: "48%",
  },
  skeletonLineWide: {
    backgroundColor: "#e2dbd1",
    borderRadius: 8,
    height: 15,
    width: "100%",
  },
  skeletonMetaLine: {
    backgroundColor: "#e2dbd1",
    borderRadius: 8,
    height: 14,
    width: "54%",
  },
  skeletonOverview: {
    gap: 10,
  },
  skeletonPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  skeletonPill: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 26,
    width: 62,
  },
  skeletonPoster: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 168,
    width: 114,
  },
  skeletonSeasonBody: {
    flex: 1,
    gap: 8,
  },
  skeletonSeasonRow: {
    alignItems: "center",
    backgroundColor: "#fffdfa",
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  skeletonSectionTitle: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 22,
    width: "42%",
  },
  skeletonTitleBlock: {
    backgroundColor: "#d8d0c5",
    borderRadius: 8,
    height: 34,
    width: "84%",
  },
  statusPanel: {
    borderColor: "#d8d0c5",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  statusTitle: {
    color: "#171412",
    fontSize: 18,
    fontWeight: "800",
  },
  title: {
    color: "#171412",
    fontSize: 31,
    fontWeight: "800",
    lineHeight: 36,
  },
});
