const colors = {
  accent: {
    border: "rgba(168, 85, 247, 0.35)",
    bright: "#A855F7",
    dark: "#5B21B6",
    primary: "#8B4DFF",
    soft: "#B56CFF",
    surface: "rgba(139, 77, 255, 0.12)",
  },
  background: {
    elevated: "#0D1420",
    primary: "#050811",
    secondary: "#080D18",
  },
  border: {
    strong: "#283246",
    subtle: "#1B2433",
  },
  rating: {
    star: "#FFB800",
  },
  status: {
    danger: "#EF5350",
    dangerDark: "#B83A3A",
    success: "#7C5CFF",
  },
  surface: {
    card: "#101722",
    cardElevated: "#141C29",
    overlay: "rgba(5, 8, 17, 0.82)",
  },
  text: {
    disabled: "#4E5665",
    inverse: "#050811",
    primary: "#F7F7FA",
    secondary: "#A7ADBA",
    tertiary: "#737B8C",
  },
} as const;

export const ui = {
  colors,
  color: {
    accent: colors.accent.primary,
    accentBorder: colors.accent.border,
    accentBright: colors.accent.bright,
    accentSoft: colors.accent.surface,
    border: colors.border.subtle,
    borderStrong: colors.border.strong,
    danger: colors.status.danger,
    dangerDark: colors.status.dangerDark,
    ink: colors.text.primary,
    muted: colors.text.secondary,
    muted2: colors.text.tertiary,
    panel: colors.surface.card,
    panelAlt: colors.background.primary,
    panelElevated: colors.surface.cardElevated,
    ratingStar: colors.rating.star,
    skeleton: colors.background.elevated,
    skeletonAlt: colors.surface.cardElevated,
    white: "#ffffff",
  },
  radius: {
    large: 16,
    md: 12,
    pill: 999,
    sm: 8,
    xl: 20,
  },
  shadow: {
    card: {
      elevation: 3,
      shadowColor: "#000000",
      shadowOffset: { height: 8, width: 0 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
    },
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  type: {
    body: 16,
    button: 16,
    display: 34,
    label: 12,
    metadata: 14,
    rowTitle: 17,
    screenTitle: 30,
    sectionTitle: 22,
    stat: 26,
  },
} as const;
